export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGIN_CHECK_STATUS = 'LOGIN_CHECK_STATUS';
export const LOGIN_RESET = "LOGIN_RESET";

export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_START = "REGISTER_START";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const DASHBOARD_SYNC_START = 'DASHBOARD_SYNC_START';
export const DASHBOARD_SYNC_STOP = 'DASHBOARD_SYNC_STOP';
export const DASHBOARD_UPDATE_TICKETS_CHART = 'DASHBOARD_UPDATE_TICKETS_CHART';
export const DASHBOARD_UPDATE_STATISTICS = 'DASHBOARD_UPDATE_STATISTICS';
export const DASHBOARD_UPDATE_PROGRESS = 'DASHBOARD_UPDATE_PROGRESS';
